### ISSUE TITLE
Step 8 in Instructions Question

### ISSUE THREAD

**Issue by cburgdorfer** [Chiogros/LinkedIn-connector-for-GDataStudio#1]
Hello Chiogros, thanks a lot for building this tool! 

I am new to both GDS and Apple Script, and I was getting stuck at step 8 of your instructions "8. Create files and set code for Core connector"

Do you have more info on what exact files to create where and what "set code for Core connector" entails? Perhaps you have a simple screenshot?

Thanks a lot!

**Comment by Chiogros** [comment]
Hello @cburgdorfer,

On 8th step, you have to implement code in your GDS connector.

Next to `appsscript.json`, you have to create files needed by Core connector (in a first time, but it is the same way for children connectors). As you can see in Core/ directory in the repository, the 4 files to create are `api.gs`, `auth.gs`, `configInputs.gs` and `core.gs` (`appsscript.json` is automatically generated by GDS).

Then for each file, you have to fill them with the code available in the repo files.

Hope it helps!

**Comment by cburgdorfer** [comment]
Hi @Chiogros great, thanks, that worked! Do I need to do anything special for the connector to appear as an available data source in GDS? I'm entering the name of the child connector in to the search bar but it doesn't seem to show up?

**Comment by Chiogros** [comment]
Hi @cburgdorfer,

Following step 9 in Child connector's README part:
`Deploy it (easiest by going through "Use old editor" > "Publish" > "Publish from manifest file")`

I know it is a non reliable way to do, but it works. If you find a more convenient way to do I'm glad to hear!
